# Generated by Django 5.1.3 on 2024-12-10 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="userimage",
            name="assigned_to_admin",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="userimage",
            name="latitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="userimage",
            name="longitude",
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name="userimage",
            name="volunteer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_images",
                to="accounts.volunteer",
            ),
        ),
    ]
