# Generated by Django 5.1.4 on 2024-12-20 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rescue", "0007_adoptableanimal_is_adoptable_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mobile_number",
            field=models.CharField(default="0000000000", max_length=15),
        ),
    ]
