# Generated by Django 5.1.4 on 2025-01-14 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerProfile',
        ),
    ]
