# Generated by Django 5.1.4 on 2025-01-20 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_volunteerlocation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VolunteerLocation',
        ),
    ]
