# Generated by Django 5.1.4 on 2025-01-22 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_delete_volunteerlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_location_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
