# Generated by Django 5.1.4 on 2025-01-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_last_location_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='last_location_update',
        ),
    ]
