# Generated by Django 5.1.4 on 2025-01-04 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdoptableAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo', models.ImageField(upload_to='animal_photos/')),
                ('is_adoptable', models.BooleanField(default=True)),
            ],
            options={
                'permissions': [('can_add_adoptable_animal', 'Can add adoptable animal')],
            },
        ),
    ]
