# Generated by Django 5.1.4 on 2024-12-23 11:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rescue", "0011_medicalrecord_added_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="medicalrecord",
            name="added_by",
        ),
    ]
