# Generated by Django 5.1.4 on 2024-12-31 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0012_remove_medicalrecord_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='NGO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
            ],
        ),
    ]
