# Generated by Django 5.1.4 on 2024-12-31 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0013_ngo'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='ngo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rescue.ngo'),
        ),
    ]
