# Generated by Django 5.1.4 on 2025-01-04 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0014_donation_ngo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AdoptableAnimal',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='ngo',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='user',
        ),
        migrations.DeleteModel(
            name='NGO',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
