# Generated by Django 5.1.4 on 2025-01-09 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0015_delete_adoptableanimal_remove_donation_ngo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
        migrations.DeleteModel(
            name='VolunteerProfile',
        ),
    ]
