# Generated by Django 5.1.4 on 2025-01-21 11:05

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0018_volunteerlocation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='animalreport',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='animalreport',
            name='longitude',
        ),
        migrations.AddField(
            model_name='animalreport',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='animalreport',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reports', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='animalreport',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ASSIGNED', 'Assigned'), ('ADMIN_REVIEW', 'Admin Review'), ('COMPLETED', 'Completed')], default='PENDING', max_length=20),
        ),
    ]
