# Generated by Django 5.1.4 on 2025-01-22 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescue', '0020_userlocationhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLocationHistory',
        ),
    ]
